### ISSUE TITLE
Application is not shutting down by pressing ctrl + c

### ISSUE THREAD

**Issue by manne** [joro550/dotnet-server#11]
## Expected behavior
Starting the application with a valid configuration file and pressing `ctrl + c` shuts down the application. As the console output states in line 7.

```
❯ .\DotNetSimpleServer.exe -fileName:..\..\..\..\..\file-example.txt
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:6000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:6001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\ZZZ\Documents\GitHub\joro550_dotnet-server\src\GlobalServer\bin\Debug\netcoreapp3.0
info: Microsoft.Hosting.Lifetime[0]
```
## Actual behavior
Starting the application with a valid configuration file (as in expected behavior) and pressing `ctrl + c` does not shut down the application. It prints out ` Application is shutting down...` and stays there.

After pressing another key shuts down the application

**Comment by joro550** [comment]
Hey - thanks for this issue! This is a funny one, because it's a console app running an asp website (esentially) I thought having one key binding to make it stop would be better than waiting for the ctrl+c input, but yeah - I think your right in saying that it's probably better to do the ctrl+c as that's what most people are used to.

**Comment by manne** [comment]
I am investigating this matter. The cause of the behavior is this line     https://github.com/joro550/dotnet-server/blob/0c66bb80e786a2836fe2d6cfc48c0d9473233f56/src/GlobalServer/Program.cs#L28

Removing that line and changing
https://github.com/joro550/dotnet-server/blob/0c66bb80e786a2836fe2d6cfc48c0d9473233f56/src/GlobalServer/Server/ServerImpl.cs#L30

to
```CSharp
return Host.RunAsync(cancellationToken);
```
results in the (my) expected behavior. However the application will only be shutdown with `ctrl + c` and not with any key.

**Comment by joro550** [comment]
Sounds like a good solution to me, I liked the sound of the one key shutdown but in practice it's sort of annoying sometimes 😆

**Comment by manne** [comment]
@joro550 To be honest, I thought the application does not shutdown after all. Until I first investigated the source code, I always killed the process 👨‍🔬

**Comment by joro550** [comment]
Ha! Yeah was maybe not the best decision, thanks for sticking with though! I have to be honest I didn't think anyone but me was using this, thanks for doing the code change, I'll give it a whirl when I'm back on my PC tomorrow.
